# Home Manager module for secretctl.
#
# Declarative wrapper around `secretctl materialize` that runs at activation
# time. Replaces sops-nix for the common pattern of writing decrypted secrets
# to ~/.config and ~/.ssh, plus generating an env-loadable shell snippet for
# token-style secrets.
#
# This module assumes the user has already run `secretctl init` and added
# the relevant secrets to their vault. It does NOT decrypt anything in Nix
# evaluation — every materialize call happens at activation time, requiring
# the macOS login keychain to be unlocked (true for any GUI session after
# user login).
#
# Example use:
#
#   programs.secretctl = {
#     enable = true;
#     envSecrets = {
#       API_TOKEN = {};
#       DEPLOY_TOKEN = { secretName = "ci_deploy_token"; };  # env var name != vault name
#     };
#     fileSecrets = {
#       SSH_PRIVATE_KEY = { path = ".ssh/id_ed25519"; mode = "0600"; };
#     };
#   };
#
# Then in your shell config:
#
#   programs.bash.initExtra = "source ~/.config/secretctl/env.sh";
{
  config,
  lib,
  pkgs,
  ...
}:
let
  cfg = config.programs.secretctl;

  envSecretType = lib.types.submodule (
    { name, ... }:
    {
      options = {
        secretName = lib.mkOption {
          type = lib.types.str;
          default = name;
          description = ''
            Name of the secret in the vault. Defaults to the env-var name
            (the attribute key). Override when the env var should be exposed
            under a different name than the vault entry.
          '';
        };
        path = lib.mkOption {
          type = lib.types.str;
          default = "${config.home.homeDirectory}/.config/secretctl/env/${name}";
          description = "Filesystem path the decrypted value is written to.";
        };
      };
    }
  );

  fileSecretType = lib.types.submodule {
    options = {
      path = lib.mkOption {
        type = lib.types.str;
        description = "Path relative to home (e.g. \".ssh/id_ed25519\") or absolute.";
      };
      mode = lib.mkOption {
        type = lib.types.str;
        default = "0600";
        description = "Octal file mode applied after writing.";
      };
      mkdir = lib.mkOption {
        type = lib.types.bool;
        default = true;
        description = "Create parent directories (mode 0700) if missing.";
      };
    };
  };

  resolvePath =
    p:
    if lib.hasPrefix "/" p then p else "${config.home.homeDirectory}/${p}";

  # home.sessionVariables don't reach the activation script, so enable the
  # key-cache agent inline here too: the first materialize unlocks (one Touch
  # ID), and the rest of this activation's secrets reuse the cached key.
  agentEnv = lib.optionalString cfg.agent.enable "SECRETCTL_AGENT=1 SECRETCTL_AGENT_TTL=${toString cfg.agent.ttl} ";

  materializeCmd =
    name: outPath: mode: mkdirFlag:
    let
      mkdir = lib.optionalString mkdirFlag " --mkdir";
    in
    ''
      ${agentEnv}${cfg.package}/bin/secretctl materialize ${lib.escapeShellArg name} \
        --out ${lib.escapeShellArg outPath} \
        --mode ${mode}${mkdir} || \
        echo "secretctl: materialize ${name} failed (vault locked?)" >&2
    '';

  envSecretLines = lib.mapAttrsToList (
    varName: spec:
    materializeCmd spec.secretName (resolvePath spec.path) "0600" true
  ) cfg.envSecrets;

  fileSecretLines = lib.mapAttrsToList (
    secretName: spec:
    materializeCmd secretName (resolvePath spec.path) spec.mode spec.mkdir
  ) cfg.fileSecrets;

  envShellFile = pkgs.writeTextFile {
    name = "secretctl-env.sh";
    text = ''
      # Generated by programs.secretctl Home Manager module.
      # Source this file from your shell rc (bash/zsh) to load env-typed
      # secrets at shell startup.
      ${lib.concatMapStringsSep "\n" (
        varName:
        let
          spec = cfg.envSecrets.${varName};
          path = resolvePath spec.path;
        in
        ''
          if [ -r ${lib.escapeShellArg path} ]; then
            export ${varName}="$(cat ${lib.escapeShellArg path})"
          fi
        ''
      ) (builtins.attrNames cfg.envSecrets)}
    '';
  };
in
{
  options.programs.secretctl = {
    enable = lib.mkEnableOption "secretctl Home Manager integration";

    package = lib.mkOption {
      type = lib.types.package;
      default = pkgs.secretctl or (throw ''
        secretctl: pkgs.secretctl is not available — either set
        programs.secretctl.package = ... explicitly, or add the
        secretctl flake's overlay to your nixpkgs config.
      '');
      description = "secretctl binary to invoke at activation.";
    };

    envSecrets = lib.mkOption {
      type = lib.types.attrsOf envSecretType;
      default = { };
      example = lib.literalExpression ''
        { API_TOKEN = {}; SERVICE_API_KEY = {}; }
      '';
      description = ''
        Secrets that should be materialized to per-var files and exposed
        as environment variables via the generated env.sh script.
      '';
    };

    fileSecrets = lib.mkOption {
      type = lib.types.attrsOf fileSecretType;
      default = { };
      example = lib.literalExpression ''
        { SSH_PRIVATE_KEY = { path = ".ssh/id_ed25519"; mode = "0600"; }; }
      '';
      description = ''
        Secrets that should be materialized to specific paths with custom
        file modes (e.g. SSH private keys).
      '';
    };

    envFilePath = lib.mkOption {
      type = lib.types.str;
      default = "${config.home.homeDirectory}/.config/secretctl/env.sh";
      description = "Where the sourceable env.sh is written.";
    };

    agent = {
      enable = lib.mkEnableOption ''
        the secretctl key-cache agent. Sets $SECRETCTL_AGENT so the first
        unlock (Touch ID / password) caches the master key in a background
        agent and subsequent commands — including `list` — skip the prompt
        for the TTL window. The key lives only in the agent's RAM; secret
        names stay encrypted at rest
      '';

      ttl = lib.mkOption {
        type = lib.types.ints.between 1 3600;
        default = 300;
        description = ''
          Sliding cache lifetime in seconds (reset on each use). Capped at
          3600 by secretctl itself. Sets $SECRETCTL_AGENT_TTL.
        '';
      };
    };
  };

  config = lib.mkIf cfg.enable {
    home.packages = [ cfg.package ];

    home.sessionVariables = lib.mkIf cfg.agent.enable {
      SECRETCTL_AGENT = "1";
      SECRETCTL_AGENT_TTL = toString cfg.agent.ttl;
    };

    home.file.".config/secretctl/env.sh" = lib.mkIf (cfg.envSecrets != { }) {
      source = envShellFile;
    };

    home.activation.secretctlMaterialize = lib.hm.dag.entryAfter [ "writeBoundary" ] ''
      $DRY_RUN_CMD mkdir -p "${config.home.homeDirectory}/.config/secretctl/env"
      $DRY_RUN_CMD chmod 0700 "${config.home.homeDirectory}/.config/secretctl/env"
      ${lib.concatStrings envSecretLines}
      ${lib.concatStrings fileSecretLines}
    '';
  };
}
