#!/usr/bin/env bash
# Manual verification of the one thing the automated suite cannot check: that a
# real authenticator app accepts this otpauth:// URI and produces codes this
# accepts.
#
# e2e_lockstate.sh already drives a locked-screen unlock end to end, but with
# codes generated by python's hmac. That proves RFC 6238 conformance. It does
# not prove that 1Password, Raivo, Google Authenticator or whatever you use
# parses *this* URI — the unpadded base32, the colon in the `secretctl:vault`
# label, the explicit algorithm/digits/period. Any of those could be mishandled
# by a specific app, and the symptom would be an "incorrect code" message that
# points nowhere.
#
# Runs on a THROWAWAY VAULT in its own $SECRETCTL_HOME, never ~/.secretctl:
#
#   * The seed it enrols is disposable. Delete that entry from your
#     authenticator when you are done — `cleanup` cannot reach into your phone.
#   * Cleanup removes this vault's two keychain items by account name. Never
#     `prune-keychain`: with a non-default home that deletes the *real* vault's
#     item, and it does not self-heal.
#
# Usage:
#   ./tests/manual_totp.sh setup     # create the vault, print the URI
#   ./tests/manual_totp.sh check     # type a code from your app
#   ./tests/manual_totp.sh cleanup

set -euo pipefail

ROOT="$(cd "$(dirname "$0")/.." && pwd)"
BIN="$ROOT/zig-out/bin/secretctl"
WORK="${SECRETCTL_MANUAL_WORK:-/tmp/secretctl-totp-manual}"
export SECRETCTL_HOME="$WORK/home"
PASS="manual-totp-throwaway"

export SECRETCTL_BATCH=1
export SECRETCTL_AGENT=0            # a warm cache would answer without a code
export SECRETCTL_BATCH_KEYCHAIN=1   # a keychain protector, so the unlock is real
# Pinned: this script tests the TOTP channel, not lock detection (already
# confirmed against a genuinely locked screen, 2fa-push-approval.md §2.1).
export SECRETCTL_FORCE_LOCKED=0

[[ -x "$BIN" ]] || { echo "binary not found: $BIN — run: zig build" >&2; exit 1; }

sc() { SECRETCTL_PASSPHRASE_FD=3 "$BIN" "$@" 3<<<"$PASS"; }

kc_account() {
  /usr/bin/od -An -v -t x1 -N 16 -j 10 < "$SECRETCTL_HOME/master.key" | tr -d ' \n'
}

case "${1:-}" in
setup)
  if [[ -d "$SECRETCTL_HOME" ]]; then
    echo "already set up at $SECRETCTL_HOME — run cleanup first" >&2
    exit 1
  fi
  mkdir -p "$WORK"
  sc init >/dev/null
  printf 'sk-totp-manual-canary\n' | sc add CANARY --tag t >/dev/null
  echo "throwaway vault at $SECRETCTL_HOME"
  echo "keychain accounts (cleanup removes both): $(kc_account) and $(kc_account)-totp"
  echo

  "$BIN" 2fa enroll

  cat <<'MSG'

------------------------------------------------------------------
Add that URI to the authenticator you actually intend to use.

  * Scanning: turn the URI into a QR however you like (secretctl does
    not print one — see the README), or paste it if your app accepts
    otpauth:// directly. 1Password and Raivo do.
  * The entry will appear as "secretctl (vault)". It is DISPOSABLE —
    delete it from the app when you finish; cleanup cannot.

  Google Authenticator quirk, observed 2026-08-25: after scanning it can
  show no confirmation at all, so the scan looks like it failed. It did
  not. Close and reopen the app and the entry is there. Do NOT rescan —
  each attempt adds another duplicate, and they all generate the same
  codes, so you cannot tell them apart afterwards.

Then: ./tests/manual_totp.sh check
------------------------------------------------------------------
MSG
  ;;

check)
  [[ -f "$SECRETCTL_HOME/master.key" ]] || { echo "not set up — run setup" >&2; exit 1; }

  echo "Read the current 6-digit code from your authenticator."
  printf 'code: '
  read -r CODE
  echo

  # 1. The code verifies at all — this is the app-compatibility question.
  if SECRETCTL_TOTP_FD=3 "$BIN" 2fa test 3<<<"$CODE" >/dev/null 2>&1; then
    echo "  ok   your app's code verifies — the URI round-trips"
  else
    echo "  FAIL your app's code did not verify."
    echo "       Most likely causes, in order:"
    echo "         - the code expired while you typed (try again, promptly)"
    echo "         - your app re-encoded the unpadded base32 wrongly"
    echo "         - your app ignored algorithm/digits/period from the URI"
    echo "       Check 'secretctl 2fa status' and the app's entry settings."
    exit 1
  fi

  # 2. The same code must now be spent. This is the property the automated
  #    suite checks with a synthetic code; here it is checked with a real one.
  if SECRETCTL_TOTP_FD=3 "$BIN" 2fa test 3<<<"$CODE" >/dev/null 2>&1; then
    echo "  FAIL the same code verified twice — replay protection is not working"
    exit 1
  else
    echo "  ok   the same code is refused the second time"
  fi

  # 3. A real unlock behind a real code, on the next one.
  echo
  echo "Now the actual unlock. Wait for your app to roll to the NEXT code."
  printf 'next code: '
  read -r CODE2
  echo
  if out=$(SECRETCTL_FORCE_LOCKED=1 SECRETCTL_TOTP_FD=3 "$BIN" list --json 3<<<"$CODE2" 2>&1) \
     && grep -q '"name":"CANARY"' <<<"$out"; then
    echo "  ok   locked screen + your app's code unlocked the vault"
    echo
    echo "PASS — your authenticator and secretctl agree. Safe to release."
  else
    echo "  FAIL unlock did not happen"
    echo "       ${out:0:300}"
    exit 1
  fi
  ;;

cleanup)
  if [[ -f "$SECRETCTL_HOME/master.key" ]]; then
    acct="$(kc_account)"
    for a in "$acct" "$acct-totp"; do
      if security delete-generic-password -s secretctl -a "$a" >/dev/null 2>&1; then
        echo "deleted keychain item $a"
      else
        echo "no keychain item $a (already gone)"
      fi
    done
  fi
  rm -rf "$WORK"
  echo "removed $WORK"
  echo "REMINDER: delete the 'secretctl (vault)' entry from your authenticator app."
  ;;

*)
  sed -n '2,26p' "$0"
  exit 2
  ;;
esac
